default_stages: [pre-commit, pre-push]
fail_fast: true

repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: trailing-whitespace
        exclude: ^exports/
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-merge-conflict
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=100"]
        exclude: |
          (?x)^(
            ^exports/|
            ^uv.lock
          )$
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-case-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.6
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: git-commit-prefix
        name: git-commit-prefix
        entry: uv run python scripts/github_commit_prefix.py
        language: python
        stages: [prepare-commit-msg]
        description: Searches the branch name for something looking like an issue name template and prepends the commit message with it
