[project]
name = "chromatica"
version = "0.0.0"
description = "Chromatica is CNN for colorization photos"
authors = [
    { name = "Mikhail Polevoda", email = "snail1704@gmail.com" }
]
readme = "README.md"

requires-python = "~=3.12.0"
dependencies = [
    "clearml>=1.18.0",
    "fastapi[standard]>=0.115.12",
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "pydantic>=2.11.4",
    "scikit-image>=0.25.2",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
    "tqdm>=4.67.1",
]

[project.scripts]
dataset_create = "chromatica.cli.dataset:create"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 88
target-version = "py312"

exclude = [
    ".git",
    ".git-rewrite",
    ".jj",
    ".ipynb_checkpoints",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    ".vscode",
    "__pypackages__",
    "build",
    "site-packages",
    "reports",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN",
  "G004",
  "D401",
  "RET504",
  "ISC001",
  "TD002",
  "FIX",
  "COM812",
]
task-tags = ["HACK", "FIXME", "TODO"]

fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"scripts/*" = ["T201", "S603"]
"notebooks/*" = ["T201", "B018", "D", "BLE001", "PLR0913", "PTH105", "C901", "PLW2901", "E501", "I001"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
notebook = [
    "ipywidgets>=8.1.7",
    "jupyterlab>=4.4.2",
]

[tool.uv]
default-groups = "all"

[tool.pyright]
venvPath = "."
venv = ".venv"
exclude = [".venv"]
pythonVersion = "3.12"
